name: pypi

on: [push, pull_request]

jobs:
  deplopy-pypi:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install necessary packages
      run: |
        python -m pip install --upgrade pip
        python -m pip install numpy setuptools build twine

    - name: Build
      run: |
        python -m build

    - name: Deploy to TestPyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      if: github.ref != 'refs/heads/master'
      run: twine upload --repository testpypi dist/*

    - name: Deploy to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      if: github.ref == 'refs/heads/master'
      run: twine upload dist/*